[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"
model_impl = "native"

train_llm = true
train_mlp = true
train_vit = true

[wandb]
run_name = "quad_node"
project_name = "mn5_check"
entity_name = "bsc_runs"

[training]
model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/qwen3vl_2b"
output_dir = "/gpfs/scratch/ehpc543/qwen_finetune/baseline_quad_node_onevision"

text_model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/qwen3_1_7b"
load_text_model = true

vision_model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/siglip2_large"
load_vision_model = true

save_steps = 500
total_steps = 3000

scheduler_type = "cosine"
warmup_steps = 250
min_lr_ratio = 0.1

lr_llm = 0.00002
lr_mlp = 0.0001
lr_vit = 0.00005

data_parallel = 'fsdp'
tp_size = 1

tpi_multiplier = 3
compile = false

[data]
data_path = "/gpfs/scratch/ehpc543/llava_recap"
seq_len = 8192

packing_buffer_size = 1_000
batch_size = 0