[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"
model_impl = "native"

[wandb]
run_name = "debug"
project_name = "fsdp debug"
entity_name = "bsc_runs"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen3_2b"
output_dir = "/data/151-1/users/shared_cache/qwen_finetune/checkpoints"

load_text_model = false

save_steps = 500
total_steps = 500

tp_size = 1
data_parallel = 'fsdp'

compile = false

[data]
data_path = "/data/151-1/datasets/llava_recap"
seq_len = 8192

packing_buffer_size = 1000

batch_size = 0
