[model]
model_name = "Qwen/Qwen3-VL-8B-Instruct"

[wandb]
run_name = "test_8b"
project_name = "test_tp"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen3_8b"
output_dir = "/data/151-1/users/tockier/qwen_finetune/checkpoints"
tpi_multiplier = 1.0

save_steps = 1000
total_steps = 1000
random_init_mlp = false

tp_size = 2
data_parallel = 'fsdp'

compile = true

[data]
data_path = "/data/151-1/datasets/synth_test_datasets/cap_pretrain"
seq_len = 2048

batch_size = 16
