[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"
model_impl = "native"

[wandb]
run_name = "qwen3-vl_2b_lumi"
project_name = "qwen3-vl_2b"
entity_name = "shanshan-wang-csc-csc"

[training]
model_dir = "cache/qwen3_2b"
output_dir = "checkpoints"

save_steps = 200
total_steps = 200

tp_size = 1
data_parallel = 'ddp'

compile = false

[data]
data_path = "/scratch/project_462001202/shanshan/synth-data-bench-training/data/cap_pretrain"
seq_len = 8192

packing_buffer_size = 100

batch_size = 0
