[model]
model_name = "Qwen/Qwen3.5-9B"
model_impl = "native"

train_llm = true
train_mlp = true
train_vit = true

[wandb]
run_name = "qwen3-5_9b_lumi"
project_name = "qwen3-5_9b"
entity_name = "shanshan-wang-csc-csc"

[training]
model_dir = "cache/qwen3_5_9b"
output_dir = "checkpoints"


save_steps = 200
total_steps = 200
warmup_steps = 50
random_init = true

data_parallel = 'fsdp'
tp_size = 4

resume_checkpoint = false


compile = false
ac_mode = "full"

[data]
data_path = "/scratch/project_462001202/shanshan/synth-data-bench-training/data/cap_pretrain"
seq_len = 4096
packing_buffer_size = 100
max_samples_per_sequence = 100

batch_size = 0