[model]
model_name = "Qwen/Qwen3.5-2B"
model_impl = "native"

train_vit = false
train_llm = true
train_mlp = true

[wandb]
run_name = "qwen3-5_2b_lumi"
project_name = "qwen3-5_2b"
entity_name = "shanshan-wang-csc-csc"


[training]
model_dir = "cache/qwen3_5_2b"
output_dir = "checkpoints"

save_steps = 100
total_steps = 100
random_init = true

scheduler_type = "cosine"

lr_llm = 2.8e-5
lr_mlp = 1.6e-4
lr_vit = 1.6e-5

tp_size = 1
data_parallel = 'ddp'

compile = false

ac_mode = 'full'

tpi_multiplier = 1

[data]

data_path = "/scratch/project_462001202/shanshan/synth-data-bench-training/data/cap_pretrain"
seq_len = 4096

packing_buffer_size = 1000
max_samples_per_sequence=400
shuffle_buffer_size=4000
batch_size = 0
